# Dependencies
markdown:         redcarpet
highlighter:      pygments
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Permalinks
permalink:        /:categories/:title
relative_permalinks: true

# Setup
title:            Prefix
tagline:          'Автоматизация и техническая поддержка IT-инфраструктуры предприятий в Шымкенте'
description:      'Автоматизация и техническая поддержка IT-инфраструктуры предприятий'
url:              http://prefix.kz
baseurl:          /

author:
  name:           'Prefix'
  url:            http://prefix.kz

paginate:         5
paginate_path:    "blog/page:num/"

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/prefixkz/prefixkz.github.io
