# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Prefix
tagline:          'Автоматизация и техническая поддержка IT-инфраструктуры предприятий в Шымкенте'
description:      'Автоматизация и техническая поддержка IT-инфраструктуры предприятий'
url:              http://prefix.kz
baseurl:          /

author:
  name:           'Prefix'
  url:            http://prefix.kz

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/prefixkz/prefixkz.github.io
